### ISSUE TITLE
"bower install" fails

### ISSUE THREAD

**Issue by goodpixels** [radum/webapp-boilerplate#1]
Hi @radum ,

When I try to run the Docker image, it bower fails with the following error:

```
Error: Bower components directory does not exist at /usr/src/webapp/bower_components
```

Can you please fix ASAP? Thanks!

**Comment by radum** [comment]
Bower install was missing, and node_modules were synced with the container, making node-sass Node binding use the local machine on the linux container. Fixed both of those issues now.
